### ISSUE TITLE
build-all issue on CircleCI???

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [conda-forge/conda-build-all#4]
We're trying to push a new recipe to staged-recipes, and keep getting:

```
+ conda build-all /root/conda-recipes --matrix-conditions 'numpy >=1.11' 'python >=2.7,<3|>=3.5' 'r-base >=3.3.2'
Fetching package metadata ...........
Resolving distributions from 1 recipes... 
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build-all", line 6, in <module>
    sys.exit(conda_build_all.cli.main())
  File "/opt/conda/lib/python3.5/site-packages/conda_build_all/cli.py", line 90, in main
    b.main()
  File "/opt/conda/lib/python3.5/site-packages/conda_build_all/builder.py", line 255, in main
    all_distros = self.compute_build_distros(index, recipe_metas, build_config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build_all/builder.py", line 220, in compute_build_distros
    self.matrix_conditions)
  File "/opt/conda/lib/python3.5/site-packages/conda_build_all/resolved_distribution.py", line 83, in resolve_all
    cases = sorted(vn_matrix.special_case_version_matrix(meta, index))
  File "/opt/conda/lib/python3.5/site-packages/conda_build_all/version_matrix.py", line 223, in special_case_version_matrix
    py_vn = minor_vn(index[python_pkg.fn]['version'])
KeyError: 'python-1.0.1-0.tar.bz2'

./scripts/run_docker_build.sh returned exit code 1
```
Which kinda looks like a bug in conda-build-all -- or in the Circle Setup???

Here's the PR:

https://github.com/conda-forge/staged-recipes/pull/3091

Travis and Appveyor take a lot longer, so who knows?

**Comment by jakirkham** [comment]
Yeah, so this is a product of `conda` 4.3 being released at `conda-forge` earlier today. We are in the process of releasing a fix in `conda-build-all` to address this. Will be restarting builds that were effected. Had to reprioritize some builds to get these releases out. Sorry for the disruption.

**Comment by jakirkham** [comment]
Already have packages for Linux and Windows released. Thus far the Linux packages appear to be working. Windows has an additional workaround (due to the feedstocks), so should be fine in either case. As Travis CI is taking a while generally, it may be a while before we see a package for macOS.

**Comment by ChrisBarker-NOAA** [comment]
I guess we just had bad timing on our attempt to get a new recipe out!

Thanks!

As y'all are on this, I'll close the issue.
